trigger:
- master

pool:
  name: Default

steps:
- script: echo Myfirst Azure Pipeline for maven project
  displayName: 'Run a one-line script'
- script: mvn clean install
  displayName: 'Build with maven'
- script: java -cp target/MavenApp-1.0-SNAPSHOT.jar com.example.App
  displayName: 'Running jar'